# Diskusjon



- Question
- Alternative
- Logic
- Methods 
- Results
- Inference



## Bergs Balanse Skala

I tverrsnittstudien til @viveiroReliabilityValidityAbility2019 sammenlignet de BBS med andre balansetester. Eldre voksne (n = 49; alder 62–90 år; gjennomsnitt = 77,8; standardavvik = 7,2) ble rekruttert fra et ideelt sykehjem. Alle deltakerne ble vurdert av 2 fysioterapeuter ved bruk av BBS, BESTest, Mini-BESTest og Brief-BESTest. Alle balansetestene viste lignende pålitelighet, reproduserbarhet og validitet. Dette tyder på at hvilken som helst av disse testene kan brukes i klinisk praksis. 
I denne oppgaven ble BBS valgt da denne er kjent for meg gjennom min bakgrunn som fysioterapeut. Den er også veldig nyttig da den tester både statisk og dynamisk balanse i både stående, sittende og ved forflytninger.

Fysisk aktivitet er helt avgjørende for å opprettholde og forbedre kondisjon, muskelstyrke og balanse hos eldre (>65 år). Dette kan bidra til å forebygge fall, samt forbedre hverdagslige funksjoner som å reise seg opp fra en stol og øke ganghastighet (Dent et al., 2018). Det er vist at individrettet trening minsker tap av fysisk funksjon hos gamle mennesker (Frändin et al., 2016), og flere meta-analyser av randomiserte, kontrollerte studier har vist at trening reduserer risikoen for fall og antall fall hos eldre (Sherrington et al., 2019; Tricco et al., 2017). I den største av disse meta-analysene fant man at trening reduserte fallraten hos eldre med 23 prosent (Sherrington et al., 2019).  

For å vedlikeholde skjelettet og forebygge brudd er det viktig å unngå inaktivitet, og selv moderat aktivitet kan ha betydning. Det gir ytterligere gevinst å drive med noe styrketrening og/eller andre vektbærende fysiske aktiviteter av høyere intensitet for å forebygge osteoporose og osteoporotiske brudd (2018 Physical  Activity Guidelines Advisory Committee, 2018).  



Kroppens funksjonsevne gir en god pekepinn på robusthet, særlig blant de eldste. I en stor dansk studie fulgte man 92- og 93-åringer over en 8-års periode, og blant menn som klarte å reise seg fra en stol uten å bruke hendene som støtte, ble hele 11 prosent 100 år (Thinggaard et al., 2016). For de som ikke klarte dette nådde kun 2 prosent 100-års alder. Tilsvarende tall for kvinner var 22 og 2 prosent. Enkle funksjonstester kan si like mye om overlevelsessannsynlighet som større helsekartlegginger.

Begrepet iboende kapasitet ble lansert av WHO i 2015, og er et mål på kroppens fysiske og mentale reserver (WHO, 2015). Disse fysiologiske reservene omfatter muligheten til å bevege seg, sensorisk kapasitet som syn og hørsel, muskelstyrke, vitalitet, kognisjon, og psykologisk kapasitet. Opprettholdelse og utvikling av iboende kapasitet vil gi eldre mulighet til å være aktive og fungere i hverdagen. Iboende kapasitet er derfor en viktig komponent for sunn aldring. Iboende kapasitet i yngre år, og i kritiske perioder i livet, kan påvirkes av en rekke biologiske, sosioøkonomiske og miljømessige faktorer og har betydning for helsen i alderdommen (Ben-Shlomo & Kuh, 2002; Hanson et al., 2016).  Funksjonsevne er en kombinasjon av personens iboende kapasitet og samspillet med miljøet personen lever i (WHO, 2015, 2021). 