project:
  type: book

book:
  title: "Masteroppgaven"
  author: "Petter Leistad"
  date: "2025-01-01"
  chapters:
    - index.qmd
    - forord.qmd
    - summary.qmd
    - 01-teori.qmd
    - 02-innledning.qmd
    - 03-metode.qmd
    - 04-resultat.qmd
    - 05-diskusjon.qmd
    - 06-referanser.qmd
    - 07-vedlegg.qmd
    - references.bib

bibliography: resources/bib-final.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



