# Innledning

<!-- Part 1: Innledning -->

---
output: html_document
editor_options: 
  chunk_output_type: console
  title: "Innledning"
output: html_document
editor_options: 
chunk_output_type: console
linestretch: 1.5
  
  
---





## Egen motivasjon og interesse

## Bakgrunn

Kreft er en fellesbetegnelse for sykdommer hvor noen av kroppens celler vokser ukontrollerbart, sprer seg til andre deler av kroppen og gir forstyrrelser av organismens normale fysiologiske funksjon (Brown et al., 2023). Studier har vist at mer enn 40% av alle kreftsykdommer er relatert til livsstil, mens resterende er relatert til genetikk. (Anand et al., 2008; Spring et al., 2015; Weiderpass, 2010). Kreft utgjør en betydelig del av sykdomsbyrden globalt, og prognoser antyder at kreftbyrden vil fortsette å øke de neste to tiårene (WHOb, 2024). Høyinntektsland står overfor en større byrde per innbygger i form av tapte leveår justert for funksjonshemming (DALYs) enn lav- og mellominntektsland (Chen et al., 2023). Selv om flere og flere får kreft, er det stadig flere som blir helt friske (Kreftregisteret, 2023) og det er rapportert om veldig mange seneffekter innenfor den biopsykososiale helsen som f.eks. redusert muskelstyrke, fatique, nevropatier, samt redusert hverdagsmestring og svekkede sosiale relasjoner (Helsedirektoratet b, 2020; Cramp et al., 2010; Philips & Currow 2010; American Cancer Society, 2022; Brown et al., 2023; Caruso et al., 2017; Pituskin, 2022). Trening, derunder styrketrening, er i økende grad blitt anerkjent for å kunne gi en rekke positive helseeffekter hos kreftpasienter, både under og etter behandling, i tillegg til at det er et forebyggende tiltak for komorbiditeter (Fairman et al., 2022; Lee, 2022; Padilha et al., 2017). Styrketrening er en effektiv metode for å forbedre styrke, kraft og balanse og skaper forutsetninger for videre progresjon i trening, funksjon og biopsykososial helse (Champ et al., 2023). Av ulike årsaker er det dessverre lav tilslutning og opptil 40% frafall (Bullard et al., 2019; Champ et al., 2023; Kampshoff et al., 2015). Geografi, ulike logistikk utfordringer, utilstrekkelig tilgang til kreftspesifikk trening og mangelfulle anbefalinger fra helsepersonell kan være årsaker til lav tilslutning og stort frafall (IJsbrandy et al., 2019). Derfor er det presserende behov for evidensbaserte, kostnadseffektive, bærekraftige og lett tilgjengelige tilnærminger for å redusere forekomsten av disse ugunstige helsekonsekvensene etter kreftbehandling og under rehabilitering. Studier har vist at hjemmebaserte treningsprogram i rehabilitering av kreftoverlevere, inkludert digital teknologi, har vist gode effekter på fysisk form og at den er logistikkmessig enklere å gjennomføre i hverdagen (Bullard et al., 2019; Driessen et al., 2017; Roberts et al., 2017). Samtidig har disse studiene svakheter ved de har undersøkt ren utholdenhetstrening eller en kombinasjon mellom utholdenhet- og styrketrening. Derfor er det behov for mer forskning på hjemmebasert styrketrening som potensielt kan rette seg mot et bredt spekter av pasienter og samtidig overkomme hindrene som begrenser deltakelse i tradisjonell trening på stedet. I Norge har «Aktiv mot kreft» etablert «Pusterom», ved 21 forskjellige sykehus, som er treningssteder for kreftpasienter under og etter behandling. I forbindelse med Covid-19 pandemien ble «Pusterommet live» og «Pusterommet hjemme» opprettet (Aktiv mot kreft Pusterommet LIVE, 2024), noe som gjør at man kan følge direktesendte eller ferdiginnspilte digitale treningsøkter uten å måtte møte på sykehus, fysioterapiklinikker eller treningssentre. Digital hjemmebasert styrketrening er derfor en fleksibel og hensiktsmessig treningsmetode hos pasienter som av ulike årsaker har utfordringer med å sikre treningskontinuitet. Det er derimot behov for klinisk relevante studier som undersøker effekten av digital hjemmetrening etter kreftbehandling, som i fremtiden effektivt kan tilbys uavhengig av pasientenes bosted.

## Formål med studien

Eksisterende studier er mangelfull på digital hjemmebasert styrketrening. Derfor er hensikten med dette oppgaven undersøke effekten av digital trening på maksimal muskelstyrke som en ny kostnadseffektiv metode som ikke påvirkes av barrierer som geografi, kultur, økonomi eller ulike logistikkmessige utfordringer.

Det overordnede målet med denne masteroppgaven er å sammenligne effekten av et 12-ukers digitalt, hjemmebasert styrketreningprogram for kreftpasienter etter fullført behandling, moten gruppe kreftpasienter som trener samme programmet med fysisk oppmøteog under veiledning av instruktør.

Det primære utfallsmålet i oppgaven er benstyrke, mens balanse og  fatique er sekundære utfallsmål.

## Oppgavens struktur

## Begrepsavklaring

**Kreft:** En fellesbetegnelse for sykdommer hvor noen av kroppens celler vokser ukontrollerbart og sprer seg til andre deler av kroppen." (Brown et al., 2023). Det er rundt 200 ulike kreftformer. De har mange fellestrekk, men det er også mye som skiller dem fra hverandre. Derfor vil sykdomsforløpet, behandling og overlevelse variere. (Kreftforeningen, 2020)

WHO definerer kreft som "en stor gruppe sykdommer som kan starte i nesten hvilket som helst organ eller vev i kroppen når unormale celler vokser ukontrollerbart, går utenfor sine vanlige grenser for å invadere tilstøtende deler av kroppen og/eller sprer seg til andre organer. Den siste prosessen kalles metastasering og er en viktig årsak til død fra kreft. En neoplasm og ondartet svulst er andre vanlige navn for kreft." (*WHOc*, 2024)

**Sykdom:** Kan bety så mangt (Hofmann & Wilkinson, 2016), men kan beskrives som en tilstand eller unormalitet som representerer en forstyrrelse av organismens normale fysiologiske funksjon (Brown et al., 2023). Kreft er en sykdom fordi kreftcellenes vekst, spredning, ressursbruk og produksjon av metabolitter, vevsforstyrrelse og inkorporering av normale ikke-kreftceller forstyrrer normale kroppsfunksjoner (Brown et al., 2023).

**Forebygging:** Trening som tiltak som er rettet mot befolkning og individ for å minimere risiko for sykdom eller funksjonshemming  (Helsedirektoratet, 2018)

**Behandling:** Formål som tar sikte på hel eller delvis helbredelse, og således endring i pasientens helsesituasjon (Helsedirektoratet, 2018)

**Trening:** En delmengde av fysisk aktivitet som er planlagt, strukturert og repetitivt med mål om å forbedre eller opprettholde fysisk form. Fysisk form er et sett med egenskaper som enten er helse- eller ferdighetsrelaterte. Fysisk aktivitet defineres som ethvert kroppslig bevegelsesmønster produsert av skjelettmuskler som resulterer i energiforbruk (Caspersen et al., 1985) 

**Styrketrening:** En treningsform som systematisk bruker motstand for å påføre musklene stress, hvilket fører til fysiologiske tilpasninger som økt muskelmasse, styrke og kraft. Dette inkluderer bruk av frie vekter, maskiner eller egen kroppsvekt som motstand. (Raastad, 2010)

Insidensen av en sykdom er definert som antall «nye» tilfeller av en sykdom i en populasjon i en definert periode. Dette tallet er anvendelig for epidemiologer, fordi det angir risikoen for en sykdom. Insidensraten er definert som insidens delt på summen av risikoperioder/situasjoner for det enkelte individ. ([Wikipedia](https://no.wikipedia.org/wiki/Insidens))

Andre begreper: Nevropati, Balanse (i ADL), fatique, maks styrke
