---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Metode

## 

Studiedesign

Denne masteroppgaven er del av et større pågående forskningsprosjekt ved Seksjon for helse- og treningsfysiologi ved Høgskolen Innlandet, i samarbeid med Sykehuset Innlandet (SI). Prosjektet er en assessor-blindet randomisert kontrollert studie (RCT), med en intervensjonsperiode på 12 uker.

## Deltagere og rekruttering

Den randomiserte kontrollerte studien (RCT) inkluderer voksne pasienter diagnostisert med hvilken som helst type kreft som har fullført aktiv sykehusbasert behandling (kjemoterapi, strålebehandling eller andre infusjonsbaserte terapier) for mindre enn fem år siden. Pasientene som bor nær Gjøvik eller Lillehammer (0-20 km reiseavstand) og som sa seg villige til å reise til «Pusterommet» ved Gjøvik sykehus eller Aktivklinikken Lillehammer for treningsprogrammet, ble randomisert til enten stedbasert veiledet styrketrening to ganger i uken eller digital hjemmebasert styrketrening to ganger i uken. Pasientene måtte også ha tilgang til digitale muligheter hjemme som gjør det mulig å delta i det alternative behandlingsopplegget. Tabell 1 viser en mer detaljert beskrivelse av inklusjons- og eksklusjonskriterier som ble brukt i denne studien.

Medisinske leger ved avdelingen for onkologi i Sykehuset Innlandet var med å rekruttere aktuelle pasienter til studien under ledelse av MD/professor Arne Kolstad. Kreftpasienter som legene var i stand til å delta i studien og som oppfylte inklusjonskriteriene uten eksklusjonskriterier til stede, ble informert om studien. Annen rekruttering av pasienter har foregått gjennom sosiale medier og andre mediekanaler. Pasienter som har vist interesse for å delta i studien har blitt kontaktet av PhD kandidaten for å kontrollere inklusjons- og eksklusjonskriteriene, samt fått mer informasjon og mottat informert samtykkeskjema. Etter innhenting av informert samtykke, har studiedeltakerne blitt inndelt i to separate grupper; 1) kvinner som har fullført aktiv behandling og bor omtrent 0-20 km fra treningsstedet, 2) menn som har fullført aktiv behandling og bor 0-20 km fra treningsstedet. Innenfor gruppene 1 og 2 ble de inkluderte deltakerne fordelt til digital hjemmebasert eller stedbasert trening i et 1:1 randomisert forhold (ved bruk av randomiseringsblokker på 10 deltakere). Randomiseringen ble utført av en forsker som ikke er involvert i prosjektet (ved bruk av R programvare).

### Inklusjons- og eksklusjonskriterier

| Inklusjonskriterier                                                                                                                                                                                         | Eksklusjonskriterier                                                                                                                                      |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------|
| ≥ 18 år og i stand til å gi informert samtykke                                                                                                                                                              | Komorbiditeter som forhindrer trening i henhold til protokollen, som alvorlige hjerte-, lunge- og andre organlidelser.                                    |
| Diagnostisert eller tidligere diagnostisert med enhver form for kreft og har fullført systemisk kjemoterapi, immunterapi eller målrettede terapier eller lokal strålebehandling for ikke mer enn 5 år siden | Tilstander forårsaket av kreft som forhindrer trening, som tidligere større kirurgi, brudd, smerte                                                        |
| Forventet levetid på mer enn 12 måneder                                                                                                                                                                     | Fremdeles under aktiv kreftbehandling som forventes å medføre høy risiko for beinmargsundertrykkelse som kan føre til                                     |
| infeksjoner, blødninger og/eller sterkt redusert fysisk kapasitet                                                                                                                                           |                                                                                                                                                           |
| Digitale muligheter hjemme: f.eks tilgang til PC og/eller iPad, e-postadresse for å logge inn på plattformen for de som tildeles digital trening                                                            | Forventet levetid på mindre enn 12 måneder                                                                                                                |
| I stand til å forstå norsk                                                                                                                                                                                  | Redusert mental kapasitet og ikke i stand til å gi informert samtykke og følge programmet                                                                 |
| Har ikke drevet med styrketrening regelmessig to ganger i uken eller mer de siste tre månedene                                                                                                              | Reiseavstand på mer enn 20 km fra hjemmet til de to treningsstedene (Gjøvik og/eller Lillehammer) for pasienter som er kandidater for stedbasert trening. |

: Tabell 1: Inklusjons-og eksklusjonskriterier

## Intervensjon

Intervensjonsgruppene hadde to økter med styrketrening per uke i en periode på 12 uker. Deltakerne i den digitale gruppen måtte ha en e-postadresse og tilgang til en PC og/eller iPad hjemme. De fikk tilgang til en lukket gruppe, kun for deltagere i dette prosjektet, på den digitale plattformen www.aktivmotkreft.no. Plattformen er en norsk, kostnadsfri digital plattform som inkluderer både direktesendte treningsøkter og forhåndsinnspilte treningsøkter. De ble bedt om å delta i forhåndsinnspilte økter som ville være tilgjengelige når de ønsket. Deltakere som ble randomisert til stedsbaserte treningsgrupper fulgte det samme treningsprogrammet under veiledning av bachelorstudenter involvert i prosjektet. Deltakerne med bosted i Gjøvik-området hadde treningsøkter på «Pusterommet Gjøvik» ved SI, mens deltakerne i Lillehammer-området hadde treninger på Aktivklinikken Lillehammer. PhD studenten og vi andre i prosjektgruppen var med på å sikre god kvalitet og opplæring av studentene. Prosjektgruppen hadde i samarbeid med «Aktiv mot kreft», utviklet og forhåndsinnspilt treningsøktene med tre forskjellige nivåer, for å sikre muligheter for tilpasning og progresjon. Varigheten av hver treningsøkt var 40 minutter (se Tabell 2 for informasjon om strukturen). Alle deltakere mottok en treningsstrikk som skulle brukes under noen av øvelsene, og for å sikre muligheter for progresjon. For å dokumentere tilslutning til treningene registrerte instruktørene oppmøte på de stedsbaserte øktene, og deltakerne i den digitale gruppen brukte en treningsdagbok for å dokumentere tilslutning (i tillegg var det mulig å hente frem dokumentasjon på på tilslutning via den digitale plattformen).

## Utfallsmål

Alle tester ble utført i laboratoriet ved Høgskolen i Innlandet, Lillehammer (HINN), med hjelp av bachelorstudenter og veiledning fra stipendiat, prosjektleder og andre forskere tilknyttet laboratoriet tilknyttet HINN.

Pre-testene ble utført i ukene 36, 37 og 38 (02.09.24 - 20.09.24), mens post-testene ble utført i ukene 49-51 (02.12.24 - 20.12.24).

Alle testene ble gjennomført på en standardisert måte. Testene som ble brukt til utfallsmål fremgår i Tabell 3 (maksimal muskelstyrketest, Bergs balanse test (BBS) og spørreskjema for fatique (Chalders fatique spørreskjema)). Alle tester ble gjennomført rett før og rett etter intervensjonsperioden. Spørreskjemaet ble på forhånd validert for kreftpasienter, og data fra normalbefolkningen er tilgjengelige for sammenligning av data. Antropometrisk data, og annen bakgrunnsinformasjon som medisinsk historie, kreftdiagnose og behandling ble registrert ved bruk av et annet spørr

## Statistikk

Statistisk styrke

Studiens hensikt har vært å undersøke treningseffekten av digital hjemmebasert versus stedsbasert styrketrening hos kreftpasienter. Hovedhypotesen forutsa at deltakere som trener hjemmebasert digital styrketrening ville oppnå samme treningseffekt på maksimal muskelstyrke som deltakere som trente i treningsstudio. Sekundære hypoteser har vært at hjemmebasert styrketrening vil forbedre balanse og fatique i samme grad som stedbasert styrketrening. Analysen ble utført i statistikkprogrammet R.

(I hovedprosjektet har man gjort beregninger for å sikre at studien har tilstrekkelig statistisk styrke. Med minst 90 % sannsynlighet kan man konkludere med at det ikke finnes en klinisk meningsfull forskjell på 5 prosentpoeng mellom gruppene (ekvivalenstest av relative endringsskårer, 𝛼 = 0,05, populasjon SD = 7,5) hvis utvalgsstørrelsen er \> 50 deltakere i hver gruppe. En utvalgsstørrelse på 49 deltakere per gruppe vil også ha \> 90 % styrke til å oppdage en forskjell mellom betingelsene tilsvarende 5 prosentpoeng. Med en forventet frafallsrate på 15-20 %, vil studien rekruttere n=60 i hver gruppe for å sikre at man ender opp med et tilstrekkelig antall deltakere til å oppnå den nødvendige statistiske styrken.)

## Organisasjon og samarbeid

Denne masteroppgaven har vært en del av et større forskningsprosjekt og har flere medlemmer fra SI, HINN, «Aktiv mot kreft», «Pusterommet Gjøvik» og Aktivklinikken Lillehammer. Medlemmene består av anerkjente forskere innen medisin, fysiologi og helse /treningsområdet, og gruppen har bred erfaring med randomiserte kontrollerte studier (RCTs). I denne masteroppgaven har mye av det praktiske samarbeidet være mellom Phd kandidat, bachelor studenter og meg selv. I tillegg har veileder Anne Mette Rustaden og andre ved HINN bistått.

## Etikk

Prosjektet hadde fått godkjenning fra Regionalt Etisk Komité for Medisinsk Forskningsetikk, Norge (REK id 553383). Alle deltakere måtte signere en skriftlig samtykkeerklæring før de ble med i studien. De ble informert om at all deltakelse er frivillig, og at de til enhver tid kunnne trekke seg fra studien, uten begrunnelse. Alle prosedyrer i prosjektet fulgte Helsinkideklarasjonen («World Medical Association Declaration of Helsinki», 2013), og prosjektprotokollen ble registrert på www.clinicaltrials.gov og www.helsenorge.no/kliniske-studier før oppstart. Alle data er blitt lagret og behandlet i Tjenester for Sensitive Data (TSD), og uten identifikasjon.

## Tidsplan

Pre-testene ble utført i ukene 36, 37 og 38 (02.09.24 - 20.09.24), mens post-testene ble utført i ukene 49-51 (02.12.24 - 20.12.24). Intervensjonsperioden foregikk i 12 uker mellom pre- og posttester.
