---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Teorigrunnlag for studien

I denne studien blir det fokusert på kreftsykdommer.

WHO definerer kreftsykdommene som en fellesbetegnelse for en rekke tilstander hvor kroppens celler vokser ukontrollert, sprer seg til andre deler av kroppen og forstyrrer organismens normale funksjon. Denne sykdomsgruppen utgjør en betydelig del av den globale sykdomsbyrden, og det er anslått at antallet krefttilfeller vil fortsette å øke de neste tiårene (Brown et al., 2023; WHO, 2024). Kreftforekomsten er sterkt påvirket av livsstilsfaktorer som tobakk, alkohol og fedme, samt økende aldring og vekst av befolkningen. I høyinntektsland opplever man et høyere tap av leveår justert for funksjonshemming (DALYs) per innbygger, enn i lav- og mellominntektsland (Chen et al., 2023).

I Norge har antall personer som får kreftdiagnose økt markant de siste tiårene, og i dag får tre ganger så mange diagnosen som for 50 år siden. Dette reflekterer både tidligere diagnostisering og forbedrede behandlingsmetoder. I 2022 ble det registrert over 38 000 nye tilfeller av kreft, og mer enn 325 000 mennesker lever med kreft i Norge i dag (Kreftregisteret, 2023). Prognosene tyder på at insidensen vil overskride 50 000 årlige diagnoser innen 2040. Selv om flere kreftpasienter overlever sykdommen, fører behandlingen med seg mange bivirkninger som kan svekke pasientens biopsykososiale helse.

Kreftbehandling kan gi både akutte og kroniske bivirkninger som påvirker pasientens fysiske og psykiske helse. Seneffekter som hjerte- og lungeskader, kognitive problemer, fatigue, hormonforstyrrelser, muskel- og skjelettskader, samt perifere nevropatier er blant de vanligste konsekvensene (Helsedirektoratet, 2020). I tillegg rapporteres om kroniske smerter, nedsatt fysisk funksjon og psykososiale utfordringer som kan påvirke livskvaliteten på lang sikt (Pituskin, 2022; Cramp et al., 2010; Philips & Currow, 2010). For mange kreftoverlevere kan disse konsekvensene gjøre daglige aktiviteter som å gå, bruke trapp, reise seg fra en stol og påkledning svært utfordrende (American Cancer Society, 2022).

Trening, spesielt styrketrening, har vist seg å ha flere positive effekter på helse og livskvalitet hos kreftpasienter både under behandling og i rehabiliteringsfasen. Til tross for dokumenterte helsefordeler, viser forskning at tilslutning til styrketrening blant kreftpasienter er lav, noe som gjør det nødvendig med evidensbaserte og tilgjengelige tilnærminger for å motvirke de negative helsekonsekvensene ved kreftbehandling.

Denne oppgaven vil undersøke anbefalinger for fysisk aktivitet og styrketrening for kreftpasienter, med fokus på effektene på muskelstyrke, muskelmasse, balanse og fatigue.

## Fysisk aktivitet og styrketrening som medisin

### Gjeldende anbefalinger for fysisk aktivitet

I følge kreftforeningen er fysisk aktivitet verdens beste medisin (Kreftforeningen, 2020). Verdens helseorganisasjon (WHO) gir generelle anbefalinger om fysisk aktivitet, inkludert de som lever med kroniske tilstander og funksjonshemninger som kreft. Disse anbefalingene (tabell 1) innebærer minst 150--300 minutter med moderat intensitet eller 75--150 minutter med høy intensitet per uke, eller en kombinasjon av begge (Bull et al., 2020). Tabellen viser også viktigheten av styrke-og balansetrening og at voksne bør ha styrketrening minimum 2 ganger pr uke og at de over 65 år bør ha minimum 3 økter pr uke med funksjonell styrke -og balansetrening.

Styrketrening er en dokumentert og effektiv metode for å forbedre styrke, kraft og balanse, hvilket er fysiske egenskaper som er viktige for den motoriske funksjon som i sin tur reduserer fallrisiko og skaper forutsetninger for videre progresjon i trening og funksjon (Champ et al., 2023).

+-------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Aldersgruppe**                                                                                            | **Anbefalinger**                                                                                                                                                                                               |
+-------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Barn og ungdom (i alderen 5--17 år), inkludert de som lever med funksjonshemninger.                         | Minst 60 minutter variert aktivitet pr dag med moderat til høyintensitet. I tillegg minst tre ganger i uka kondisjonsrettet med høy intensitet som inkluderer aktiviteter som styrker muskler og skjelett.     |
+-------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Voksne (i alderen 18--64 år), inkludert de med kroniske tilstander og de som lever med funksjonshemninger.  | Regelmessig fysisk aktivitet. Hver uke være fysisk aktive i minst 150 til 300 minutter med moderat intensitet, minst 75 til 150 minutter med høy intensitet eller en kombinasjon av moderat og høy intensitet. |
|                                                                                                             |                                                                                                                                                                                                                |
|                                                                                                             | Voksne bør også utføre styrketrening som involverer alle store muskelgrupper på 2 eller flere dager i uken, da dette gir ytterligere helsefordeler.                                                            |
+-------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Eldre voksne (65 år og eldre), inkludert de med kroniske tilstander og de som lever med funksjonshemninger. | Samme råd som hos voksne, men i tillegg ha minimum 3 økter i uken med funksjonell styrke og balansetrening for å forebygge fall i funksjon og fall-risiko.                                                     |
+-------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Tabell 1: Sammendrag av WHO-retningslinjene om fysisk aktivitet. Retningslinjene gjelder for alle befolkningsgrupper fra 5 år og eldre, uavhengig av kjønn, kulturell bakgrunn eller økonomisk status. Personer kroniske medisinske tilstander og/eller funksjonshemninger, bør forsøke å oppfylle disse anbefalingene når det er mulig og etter evne. (Bull et al., 2020)

I gjennomføringen av disse anbefalingene anbefaler Helsedirektoratet at kreftoverlevere følger disse retningslinjene, men at prinsippet om progresjon med varighet og intensitet bør ivaretas. For eksempel foreslås det å starte med 15--20 minutter med moderat fysisk aktivitet, som ergometersykling eller gange i motbakke, tre ganger per uke, og gradvis øke intensiteten over tid. [Helsedirektoratet](https://www.helsedirektoratet.no/rapporter/seneffekter-etter-kreftbehandling/?utm_source=chatgpt.com)

Kreftforeningen anbefaler også at ferdigbehandlede kreftpasienter gradvis øker til minst 30 minutter med moderat fysisk aktivitet daglig, som rask gange. Når man er i stand til det, bør intensiteten økes slik at man blir svett, andpusten og får økt puls.

Gjeldende anbefalinger tilsvarer omtrent 7,5--15 MET-timer (Metabolic Equivalent of Task) per uke. En MET er en enhet som representerer energiforbruket i hvile. Aktiviteter med moderat intensitet, som rask gange, har en MET-verdi på omtrent 3--6, mens høyintensive aktiviteter, som løping, har høyere MET-verdier. For eksempel vil 150 minutter med en aktivitet på 5 MET per uke gi totalt 12,5 MET-timer.

Meta-analysen til @liDoseResponseEffect2016 konkluderer med at de nåværende anbefalingene for fysisk aktivitet er tilstrekkelige for å redusere kreftdødelighet. Så mye som 21% redusert kreftdødelighet er vist hos kvinner. Tilsvarende effekt er derimot ikke observert hos menn. De har også studier som viser at fysisk aktivitet beskytter spesielt mot bryst-, kolorektal- og prostatakreft. Mekanismene bak er vist i tabell 2. Dette understreker viktigheten av en aktiv livsstil i både forebygging og oppfølging etter kreftdiagnose.

+--------------------------+-----------------------------------------------------------------------------+
| **Mekanismeområde**      | **Forklaring**                                                              |
+==========================+=============================================================================+
| Metabolske endringer     | \- Lavere kroppsmasseindeks (BMI)                                           |
|                          |                                                                             |
|                          | \- Redusert fettvev (adipositas)                                            |
+--------------------------+-----------------------------------------------------------------------------+
| Hormonelle påvirkninger  | \- Reduserte nivåer av kjønnshormoner                                       |
|                          |                                                                             |
|                          | \- Lavere nivåer av insulin og c-peptid                                     |
+--------------------------+-----------------------------------------------------------------------------+
| Reduksjon i inflammasjon | \- Mulige reduserte betennelsesprosesser i kroppen                          |
+--------------------------+-----------------------------------------------------------------------------+
| Forbedret immunfunksjon  | \- Potensielle forbedringer i immunforsvarets funksjon                      |
+--------------------------+-----------------------------------------------------------------------------+
| Bedre insulinfølsomhet   | \- Økt insulinsensitivitet, som er spesielt relevant for enkelte krefttyper |
+--------------------------+-----------------------------------------------------------------------------+

Tabell 2: En oppsummering av mekanismene som potensielt bidrar til den beskyttende effekten fysisk aktivitet har på kreftdødelighet. @liDoseResponseEffect2016

Andre referanser?

#### Styrketrening som terapeutisk intervensjon (skrive det sånn eller som ved styrketrening som medisin)

Styrketrening har vist seg å være en viktig komponent i rehabilitering og sykdomsforebygging blant kreftpasienter. Den bidrar til å redusere risikoen for komorbiditeter, forbedre behandlingsresultater og fremme fysisk funksjon (Fairman et al., 2022; Lee, 2022). Likevel er styrketrening underutnyttet i klinisk praksis, og deltakelsen blant pasientene er lav (Champ et al., 2023).

Sarkopeni er en sentral utfordring for kreftpasienter, karakterisert ved redusert muskelmasse, styrke og funksjonsevne (Cruz-Jentoft et al., 2019). Denne tilstanden kan være primær (aldersrelatert) eller sekundær, forårsaket av sykdom eller behandling. Kjemoterapi-indusert perifer nevropati (CIPN) er en vanlig bivirkning som forverrer sarkopeni ved å påvirke muskelkontroll, balanse og styrke negativt (Seretny et al., 2014).

##### Fysiologiske og funksjonelle fordeler ved styrketrening

Styrketrening er blant de mest effektive metodene for å motvirke muskelatrofi og redusert fysisk funksjon. Studier har vist at regelmessig styrketrening kan øke muskelstyrken med opptil 42 % hos eldre, forbedre ganghastighet og styrke evnen til å reise seg fra en stol (Dent et al., 2018; Marzuca-Nassr et al., 2024). Studien til @marzuca-nassrMuscleMassStrength2024 videre at alle deltakerne økte tverrsnittsarealet for quadriceps, med en økning som varierte fra [1% til 18%]{.underline} hos 65--75 åringene og fra [6% til 21%]{.underline} hos deltagerne over 85 år. De ble også henholdsvis 38% og 42% sterkere, samt 8% og 12% raskere. Slike forbedringer reduserer risikoen for fall, fremmer selvstendighet og styrker livskvaliteten (Sherrington et al., 2019).

Fysiologisk stimulerer styrketreningen proteinsyntesen, forbedrer mitokondriell funksjon og reduserer opphopningen av skadede proteiner i muskulaturen (Irving et al., 2012; Hood et al., 2019). Samtidig fører treningen til frigjøring av myokiner, som har anti-inflammatoriske effekter og styrker immunforsvaret (Tagliafico et al., 2022). Disse mekanismene er særlig viktige for å redusere aldersrelaterte funksjonsnedsettelser og fremme helhetlig helse.

##### Fallforebygging og balansetrening

Integrering av balansetrening med styrketrening er avgjørende for å redusere fallrisiko, særlig blant eldre. Fallrelaterte skader utgjør en betydelig samfunnsøkonomisk byrde og er blant de mest kostbare helseutfordringene for eldre i Norge (Kinge et al., 2023). Kreftpasienter er spesielt utsatt for balanseproblemer, noe som ofte skyldes nevrotoksiske effekter av kjemoterapi (Marshall et al., 2017).

Det er sett at fall kan bidra til inaktivitet som igjen bidrar til ytterligere funksjonsnedsetting og reduksjon i helhetlig helse.

Tilpassede treningsprogrammer som kombinerer balanse- og styrketrening har vist seg effektive for å bedre fysisk funksjon og redusere alvorlighetsgraden av fall (Montero-Odasso et al., 2022). Som for eksempel kan en opplæring i funksjonelle ferdigheter, som å kunne reise seg fra gulvet, ha en viktig rolle i å redusere konsekvensene av fall.

##### Barrièrer for deltakelse og tiltak for fremme av styrketrening

Til tross for styrketreningens godt dokumenterte fordeler, er deltakelsen blant kreftpasienter lav. Frykt for skade, manglende veiledning og kunnskap, og begrenset tilgang til tilrettelagte treningsfasiliteter er vanlige barrièrer (Champ et al., 2023). Initiativ som "Aktiv mot kreft" og etableringen av Pusterom, treningssentre spesielt designet for kreftpasienter, har vist seg effektive i å fremme fysisk aktivitet.

##### Konklusjon

Styrketrening representerer en kraftfull intervensjon for å bedre muskelstyrke, funksjonsevne og livskvalitet hos både eldre og kreftpasienter. For å realisere dette potensialet kreves systematiske tiltak for å integrere styrketrening i behandlingsforløpene, samt økt fokus på kompetansebygging blant helsepersonell og pasienter. En slik tilnærming vil kunne bidra til betydelige helsegevinster og redusert samfunnsøkonomisk byrde.

## Styrketrening som medisin

Styrketrening er i økende grad blitt anerkjent som gunstig i behandling for mennesker som lever med kreft som en kronisk sykdom, i tillegg til at det er et forebyggende tiltak for komorbiditeter (Fairman et al., 2022; Lee, 2022; Padilha et al., 2017).

Det er kjent at et progressivt tap av skjelettmuskel har negative kliniske konsekvenser på muskelstyrke, respirasjonsfunksjon, funksjonsstatus, funksjonshemmingsrisiko og livskvalitet [@muscaritoliConsensusDefinitionSarcopenia2010], og at lav muskelstyrke er assosiert med ugunstige helseutfall som fall- og bruddskader @schaapAssociationsSarcopeniaDefinitions2018.

Samtidig vet man at styrketrening ikke har blitt en rutinemessig del av behandling og rehabilitering, og at det dessverre lav tilslutning til denne treningsformen blant kreftpasienter (Champ et al., 2023).

### Sarkopeni og dens konsekvenser

Sarkopeni og overvekt er signifikante utfordringer hos mennesker med kreft, både under og etter kreftbehandling (Champ et al., 2023). Cruz-Jentoft et al. (2019) definerer sarkopeni som *et muskelsvinn-syndrom kjennetegnet ved lav muskelmasse, lav muskelstyrke og/eller lav fysisk funksjon* (f.eks. lav ganghastighet). I deres konsensusdefinisjon for "European Working Group on Sarcopenia in Older People (EWGSOP2)" legger de vekt på muskelstyrke som det mest avgjørende elementet, siden styrke er sterkere assosiert med funksjonelle utfall enn muskelmasse alene.

(Sarkopeni kommer gjerne fra flere faktorer og deles inn i primær og sekundær sarkopeni. Sarkopeni, sarkopeni kakeksi, sarkopeni obesity [@anjanappaSarcopeniaCancerRisking2020].)

Det er også beskrevet at både muskelstyrke og muskelmasse virker å kunne gi både informativ og prediktiv verdi for kreftprognose @caoEffectExerciseSarcopenia2022. Studien til (Miyamoto et al., 2015) fremhever sarkopeni som en mulig prediktiv faktor for overlevelse etter gjennomgått behandling. Det er også sett at kreftpasienter og kreftoverlevere med lav muskelmasse har en økt risiko for akutt kardiovaskulær sykdom (Zhang et al., 2023).

I studien til @morishitaDifferencesRelationshipsMuscle2022 konkluderte de med at eldre brystkreftoverlevere har betydelig lavere muskelstyrke (og muskelmasse) enn middelaldrende.

Fysisk skrøpelighet kjennetegnes ved redusert muskelstyrke, redusert energinivå og økt trettbarhet, utilsiktet vekttap og lav fysisk aktivitet (Clegg, Young, Iliffe, Rikkert, & Rockwood, 2013; Rodriguez-Manas & Fried, 2015). De fysiologiske reservene i kroppen blir redusert, og motstandskraften mot påkjenninger som sykdommer og skader blir dårligere. 

Helsedirektoratet råd for fallforebygging hos eldre viser til at balanse- og styrketrening styrker beinhelsen og bidrar til å forhindre fall og fallrelaterte skader. Styrketrening øker muskelstyrken og kan øke beinmineraltettheten i knoklene, noe som styrker dem ved et eventuelt fall. Fysisk aktivitet og fallforebyggende trening kan ha betydning for hvor lenge en person kan bo hjemme og klare seg selv. Aldringsprosessen fører til endringer i de fleste av kroppens organer og en generell nedgang i både fysisk og mental kapasitet. Daglig fysisk aktivitet og trening kan bidra til at prosessen utsettes. Mange av hverdagens gjøremål stiller krav til både muskelstyrke og balanse. For eksempel er det avgjørende med muskelstyrke i beina for å kunne reise seg fra en stol og gå i trapp på egen hånd. Det å forflytte seg på egen hånd og bevege seg fritt både innendørs og utendørs krever både muskelstyrke og balanse. Av disse grunner er det svært viktig å trene styrke og balanse for å bevare mest mulig selvstendighet i hverdagen. Bevegelsesvansker og tap av selvstendighet er ofte årsak til at eldre får behov for hjelp i hjemmet (Wyller, 2016; Størksen, 2016). Å lære seg ferdigheten å kunne reise seg fra gulvet selv dersom man faller er viktig fordi det å ligge på gulvet i mer enn en time er assosiert med dehydrering, elektrolyttforstyrrelser, nyresvikt, hypotermi, lungebetennelse og urinveisinfeksjoner, hudskader og smerter og nedsatt bevegelighet og begrensinger i aktivitet, trolig på grunn av bekymringer for å falle på nytt (Montero-Odasso et al., 2022).

### Viktigheten av styrketrening

Styrketrening er vist å kunne motvirke fall i muskelmasse, -styrke og -kraft hos eldre personer [@marzuca-nassrMuscleMassStrength2024]. Studien viste at alle deltakerne økte tverrsnittsarealet for quadriceps, med økningen som varierte fra [1% til 18%]{.underline} hos 65--75 og fra [6% til 21%]{.underline} hos 85+. De ble også henholdsvis 38% og 42% sterkere, samt 8% og 12% raskere.

Styrketrenings gode effekter på økt muskelfunksjon kan forklares med at den stimulerer til økt proteinomsetning, og kan redusere opphopningen av skadede proteiner (Irving et al., 2012). Den gir også økt produksjon og frigjøring av myokiner som har en rekke gunstige påvirkninger som redusert systemiske inflammasjon og økt immunrespons (Tagliafico et al., 2022) og vil forbedre kvaliteten på mitokondriemengden i musklene, med den overordnede effekten av å forbedre muskelfunksjonen (Hood et al., 2019).

Styrketrening vil også forbedre hverdagslige funksjoner som å reise seg opp fra en stol og øke ganghastighet (Dent et al., 2018). Tilpasset styrketrening har vist å redusere funksjonstapet hos eldre (Frändin et al., 2016), og flere meta-analyser har vist at trening reduserer risikoen for fall og antall fall hos eldre (Sherrington et al., 2019; Tricco et al., 2017). I den største av disse meta-analysene fant man at trening reduserte fallraten hos eldre med 23 prosent (Sherrington et al., 2019).

Styrketrening gir også en økning i muskelmasse hos disse pasientene selv om det er mer sprikende funn på dette området (Champ et al., 2023; Lee, 2022; Nilsen et al., 2015).

Målene ved styrketrening innenfor kreft er å optimalisere styrketreningen for hver enkelt pasient for å påvirke styrke og bevegelighet, prestasjon og funksjon, og kroppssammensetning (Champ et al., 2023).

## Balansetrening

### Balanseutfordringene og trening av balanse

Det er beskrevet at kreftpasienter har redusert balanse (Morishita et al., 2022) og at så mange som 20% av kreftoverlevere rapporterer balanseutfordringer [@chevilleDetectionTreatmentCancerrelated2009]. I tillegg er over 60% av kreftoverleverne over 65 år [@medinaBalanceVestibularFunction2021] , og økende alder er i seg selv en risikofaktor for nedsatt balanse, da gjerne sett i sammenheng med nedsatt muskelstyrke i beina. Dette gir gjerne en selvforsterkende effekt med økende inaktivitet. For det er slik at ca 1/3 av alle over 65 år har ett eller flere fall pr år og at risikoen for fall og fallrelaterte skader øker videre med alderen, og at fall er assosiert med redusert livskvalitet grunnet redusert fysisk funksjon og sosial omgang. [@sherringtonExercisePreventingFalls2019].

I tillegg har eldre brystkreftoverlevere betydelig lengre COP-lengde (trykksenter) enn middelaldrende @morishitaDifferencesRelationshipsMuscle2022.

Fall har store samfunnsmessige konsekvenser, både for den enkelte, pårørende og alle nivåer i helsetjenesten.

Andre konsekvenser er engstelse for nye fall, immobilitet og økt behov for helse- og omsorgstjenester (Olsen et al., 2017). Det er beregnet at fall utgjør den nest mest kostbare tilstanden i Norge i 2019 etter demens, med anslåtte helsekostnader på 14.5 milliarder NOK (Kinge et al., 2023). Dette tallet innebefatter behandling av fallskader, og hoftebrudd er blant de mest kostnadskrevende enkeltdiagnosene for eldre pasienter i spesialisthelsetjenesten. Fall som resulterer i hoftebrudd medfører høy overdødelighet (Holvik et al., 2023), redusert selvhjulpenhet, økt pleiebehov og etter hvert behov for sykehjemsplass for mange. På grunn av økningen av antallet eldre i de kommende årene, særlig fra 2025.

Hvert å faller omtrent 30 prosent av alle over 65 år og hele 50 prosent av dem som er over 80 år. Funksjonssvikt, inaktivitet, isolasjon, nedsatt livskvalitet, økt hjelpebehov og tidligere død er noen av konsekvensene et fall kan innebære for eldre. Balanseøvelser og aktivitet som øker kjernemuskulatur og styrke kan forebygge fall. (https://sykepleien.no/meninger/2024/05/vi-ma-gjore-mer-forebygge-fall-blant-eldre)

I @mullerOutBalancePostural2020 så man at kreftpasienter viser betydelig balansesvikt etter nevrotoksisk kjemoterapi, at den reduserte balansen er mest tydelig under visuell deprivasjon (lukkede øyne) og at den er sterkest assosiert med nerveledningshastighet

#### Nevropati som påvirkende faktor på redusert balanse

Kjemoterapi-indusert perifer nevropati (CIPN) er en invalidiserende smertetilstand @seretnyIncidencePrevalencePredictors2014 og har også vist seg å være en risikofaktorer for balanseproblemer hos kreftoverlevere @marshallChemotherapyinducedperipheralNeuropathyGait2017

I en tidligere oversiktsartikkel og meta-analyse @seretnyIncidencePrevalencePredictors2014 så man at CIPN-prevalensen var 68,1 % (57,7--78,4) målt i den første måneden etter kjemoterapi, 60,0 % (36,4--81,6) etter 3 måneder og 30,0 % (6,4--53,5) etter 6 måneder eller mer.

### Fatigue blant kreftoverlevere og effekten av trening

Tidligere diagnostisering, bedre behandling og overlevelse de siste tiårene har sine fordeler. Samtidig viser økt overlevelse seg å gi en økning i bieffekter som fatigue @mullerOutBalancePostural2020.

NCCN definerer kreftrelatert fatique som "en plagsom, vedvarende, subjektiv følelse av fysisk, emosjonell og/eller kognitiv tretthet eller utmattelse relatert til kreft eller kreftbehandling som ikke står i forhold til nylig aktivitet og forstyrrer vanlig funksjon." (Sanft et al., 2023)

Fatigue er nesten universell under kreftbehandling og flere studier har vist at fatigue kan vedvare i opptil 10 år hos over 25% av kreftoverlevere. Dette har stor innvirkning på disse menneskenes livkvalitet i både daglige aktiviteter, på jobb og sosialt (Bower, 2014).

I tillegg kan fatique være med på å bidra til balanseproblemer og \@huangFactorsAssociatedSelfreported2018 så en tydelig sammenheng mellom fatigue og nedsatt balanse hos kreftoverlevere. De beskriver at fatigue er med på å redusere muskelstyrke- og utholdenhet som igjen svekker både dynamisk og statisk balanse.

Det er også at sett en korrelasjon mellom høy grad av fatique og lav benstyrke, samt høy fettprosent og aktivitetsnivå blant kreftoverlevere. (Winters-Stone et al., 2008).

Selv om det fortsatt er en viss usikkerhet om fordelene ved trening for å redusere kreftrelatert tretthet (CRF) generelt, er det overbevisende bevis på at trening ikke øker CRF. (Thong et al., 2020). Og det er vist er at fysisk aktivitet bidrar til lavere grad av fatique, og noen studier på styrketrening viser det samme.....

GÅ GJERNE MER RETT PÅ HVA STYRKETRENING VISER PÅ DISSE VARIABLENE

GJERNE NOE OM BARRIERER FOR STYRKETRENING, AKTIV MOT KREFT OG PUSTEROMMENE

## Tidligere studier på styrketrening på kreftpasienter

### Etterlevelse av denne treningen

Generelt viser det seg...

### Hjemmebasert styrketrening

### Styrketrening på treningstudio

JA, FÅ MED LITT OM HVA VI VET OM EFFEKTEN AV STYRKETRENING PÅ KREFTPASIENTER, MEN AT DETTE FORUSETTER AT TRENINGEN GJENNOMFØRES. SKRIV GJERNE OM FORDELER OG ULEMPER MED DE ULIKE TRENINGSFORMENE, OG AT DET ER VIKTIG Å FINNE KOSTNADSEFFEKTIVE PROGRAMMER SOM ENKELT KAN IMPLEMENTERES TIL PASIENTER UAVHENGIG AV HVOR DE BOR, OG HVOR LANG REISEVEI DE HAR TIL NÆRMESTE PUSTEROM ELLER ANDRE TRENINGSLOKALER SOM KAN TILBY KREFTRELATERT TRENING.

Definisjoner
